- package-lock.json
- prisma/migrations/20240510144252_/migration.sql
- prisma/migrations/20240510160104_fix_id/migration.sql
- prisma/migrations/20240512193407_lang/migration.sql
- prisma/schema.prisma
- src/controller/authController.ts
- src/controller/creatorController.ts
- src/controller/userController.ts
- src/routes/creatorRoute.ts
- src/routes/index.ts
- src/routes/userRouter.ts
- src/service/RegisterService.ts
- src/service/userServices.ts
- yarn.lock
> new creator functions

- prisma/migrations/20240626052111_/migration.sql
- src/controller/campaignController.ts
- src/routes/campaignRoute.ts
> Begin implementing campaign editing

- prisma/schema.prisma
- src/controller/bugController.ts
- src/routes/bugRoute.ts
- src/routes/index.ts
- src/service/google_sheets/sheets.ts
> implementing bug form in the platform

- prisma/schema.prisma
- src/controller/acessController.ts
- src/controller/campaignController.ts
- src/routes/accessRoute.ts
- src/routes/index.ts
- src/service/publicService.ts
- yarn.lock
updated prisma schema, to avoid any errors or duplications in db
> public access routes

- package.json
- prisma/manageCompanyData.ts
- prisma/schema.prisma
- prisma/seed.ts
- prisma/seedCompany.ts
- src/controller/campaignController.ts
- src/controller/companyController.ts
- src/routes/campaignRoute.ts
- src/routes/companyRoute.ts
- src/service/companyService.ts
> feat(company): update new flow for creating a company

- prisma/schema.prisma
- src/controller/campaignController.ts
> added KWSP field and function

- prisma/schema.prisma
- src/controller/campaignController.ts
> currency added

- prisma/schema.prisma
> removed amount

- src/controller/authController.ts
- src/controller/creatorController.ts
- src/helper/creatorsSpreadsheetService.ts
- src/helper/registeredCreatorSpreadsheet.ts
- src/routes/creatorRoute.ts
This pull request introduces a new feature to export registered creators' data to a Google Spreadsheet from the Creator Table View. Here are the key updates included in this pull request:
1. **New Export Functionality**:
- Added a button labeled "Google Spreadsheet" in the Creator Table View interface.
- Clicking the button triggers the `handleExportToSpreadsheet` function, which initiates an API call to fetch the spreadsheet data and opens it in a new tab.
- The button provides user feedback by displaying "Exporting..." while the export process is ongoing and disables itself temporarily during this process.
2. **API Integration**:
- A new API endpoint, `/api/creator/exportCreators`, has been added to the `endpoints` object in `src/utils/axios.js`. This endpoint facilitates the export …
> CC-0001 Registered users spreadsheet for Super Admin

- src/controller/authController.ts
- src/controller/creatorController.ts
- src/helper/creatorsSpreadsheetService.ts
- src/helper/registeredCreatorSpreadsheet.ts
- src/routes/creatorRoute.ts
Merge Esther update for creator register spreadsheet into main branch
> Ccb 0001 registered users spreadsheet

- src/auth/googleAuth.ts
- src/controller/authController.ts
- src/controller/creatorController.ts
- src/helper/creatorsSpreadsheetService.ts
- src/helper/formateDateTime.ts
- src/helper/registeredCreatorSpreadsheet.ts
- src/service/creatorsSpreadsheetService.ts
Enhanced the creator spreadsheet export functionality by adding two new data fields: **Date Registered** and **Social Handle**. This provides better tracking and visibility of creator registration patterns and social media presence.
```typescript
const CREATOR_HEADERS = [
'Name', 
'Email', 
'Phone Number', 
'Country', 
'Date Registered',    // ← NEW
'Social Handle'       // ← NEW
];
```
- Modified `exportCreatorsToSpreadsheet()` to include new fields in database query
- Added social media data joins for Instagram and TikTok users
- Implemented smart updating for existing rows missing the new fields
- Added data formatting for consistent social handle display
- Updated `saveCreatorToSpreadsheet()` to include registration date on new creator signup
- Maintains backward compatibility with …
> CCD-100 Update: registered users sheet with new columns

- src/controller/submissionController.ts
- src/service/submissionService.ts
- Fixed congrats message issue
- Fixed to ensures that isCampaignDone is only set to true
> Fix congrats message issue

- src/service/creatorsSpreadsheetService.ts
The creators export function was failing with a "Quota exceeded for quota metric 'Write requests'" error when trying to update a large number of spreadsheet rows (1600+ users). The original implementation was updating rows one by one, causing us to hit Google's API rate limits.
Batch Operations: Implemented batch updates using Google Sheets batchUpdate API to group multiple row updates into single requests
Rate Limiting: Added delays between batches and retry logic with exponential backoff
Chunking: Process updates in smaller chunks (10 rows per API call, 50 users per batch) to stay within quotas
Optimized Database Queries: Fetch users in batches of 500 instead of loading all at once
Replaced individual row.save() calls with batch API operations
Added retry mechanism for failed requests …
> Fix: Optimize creators spreadsheet export to handle Google Sheets API rate limits

- src/controller/socialController.ts
- src/service/socialMediaService.ts
This PR implements automatic TikTok token refresh functionality to resolve issues with expired tokens when fetching content performance data. Users will no longer experience failed requests due to token expiration.
**Related Issue:** https://github.com/ccasia/cc-backend/pull/157
- **Added `refreshTikTokToken()` function** in `socialMediaService.ts`
- Handles TikTok API token refresh requests
- Proper error handling for failed refresh attempts
- **Added `ensureValidTikTokToken()` helper function** in `socialController.ts`
- Validates token expiration using stored timestamps
- Automatically refreshes expired tokens
- Updates database with new encrypted tokens
- **Updated `getTikTokVideoInsight()` endpoint**
- Now uses automatic token validation before API calls
- Provides clear error …
> CCD-099 Feature: Content performance reporting tool v4

- prisma/cleanup-test-users.ts
- prisma/schema.prisma
- src/config/nodemailer.config.ts
- src/controller/authController.ts
- src/controller/clientController.ts
- src/controller/companyController.ts
- src/middleware/adminOrClient.ts
- src/middleware/clientOnly.ts
- src/routes/authRoute.ts
- src/routes/clientRoute.ts
- src/routes/companyRoute.ts
- src/routes/index.ts
- src/service/userServices.ts
- Add complete client registration system with password setup and verification
- Implement client portal invitation system via email
- Add client-admin relationship model with proper role management
- Create client profile update functionality with company email support
- Add cleanup scripts for test users and database maintenance
- **Database Schema**: Updated client model to include admin relationship, company connection, and invite token
- **Authentication**: Added client registration, verification, and password setup endpoints
- **Email System**: Implemented client invitation and verification email templates
- **Profile Management**: Added client profile update with company email functionality
- **Database Tools**: Created comprehensive test user cleanup script with batch processing
- …
> CCD-163 Feature: Client Auth Flow

- src/helper/videoDraft.ts
- src/helper/videoDraftWorker.ts
When notification is saved on "New Draft Received" for admins, the data fetched now includes the creator's user ID.
> CCD-166 Fix: Nofication route for creator deliverables

- prisma/seed.ts
- Added CS Lead role with appropriate permissions for campaign and client management
- Enhanced client model with admin relationship and company association           
- Improved seed file to support multiple roles and proper permission assignment                                                                                         
- **Schema Updates**: Added CS Lead designation, client-admin relationships, pitch approval workflows
- **Role Management**: Added CS Lead role with campaign and client management permissions
> CCD-183 Feat: Add CS Lead role

- src/controller/campaignController.ts
Fix CSL role view issues as related to https://github.com/ccasia/cc-frontend/pull/300
> CCD-205 Fix: CSL role views

- src/controller/socialController.ts
- src/routes/socialRoute.ts
- src/service/socialMediaService.ts
This PR resolves the issue where the media kit did not function for users who connected their TikTok accounts. The root cause was a missing function—responsible for calling the TikTok data endpoint—leading to the failure in fetching and displaying TikTok analytics and profile details in the media kit.
When users connected their TikTok accounts, the media kit failed to retrieve TikTok profile and analytics data. This was traced to the absence of a key function in the backend. As a result, the application did not hit the endpoint required to fetch TikTok data, so no information was returned for TikTok-connected users.
- **Added the missing function** for fetching TikTok data, ensuring the backend now correctly calls the TikTok API endpoint.
- Implemented necessary controller and service …
> CCB-404 Fix: TikTok media kit missing function

- prisma/schema.prisma
- src/controller/campaignController.ts
- src/routes/campaignRoute.ts
- src/service/shortlistService.ts
Allow admins to shortlist creators that are not currently on the platform to campaigns
> CCD 202 Feat: Shortlisting non platform creators

- prisma/schema.prisma
- src/controller/pitchController.ts
Added adminComment fields in schema.prisma and updated controller function to handle adminComments
> CCD 201 Feat: admin comment field 

- prisma/schema.prisma
- src/controller/creatorSubmissionV4Controller.ts
- src/controller/submissionV4Controller.ts
- src/routes/submissionV4Route.ts
- src/service/submissionV4Service.ts
- src/utils/captionHistoryUtils.ts
This pull request introduces a caption history feature for submissions, allowing tracking of all changes to captions and who made them. It includes database schema changes, backend logic to save caption updates, and a new API endpoint to fetch caption history. Additionally, it refines feedback filtering logic for submissions.
> CCD-268 Feat: Feedback & Caption Logs
